version: 0.1
phases:
   build:
    commands:
      - aws cloudformation package --template-file ./codebuild/stage/stageTemplate.yaml --s3-bucket s3-lifestyle-dev --s3-prefix codebuild-artifacts/lifestyle --output-template-file newStageTemplate.yaml
artifacts:
  type: zip
  files:
    - newStageTemplate.yaml
cache:
  paths:
    - pip_dir/**/*
