AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Test automatic deployment or update of Lambda functions
Resources:
    LifestyleAddItem:
        Type: AWS::Serverless::Function
        Properties:
            Description: Add items to dynamodb
            FunctionName: lifestyle-additem
            Handler: cron_process.add_item
            MemorySize: 128
            Role: arn:aws:iam::794633948264:role/lifestyle-lambda-role
            Runtime: python3.6
            CodeUri: ../
            Timeout: 30
            VpcConfig:
                SecurityGroupIds: [sg-053b844bbd96ee0cc]
                SubnetIds: [subnet-047d1ae6d1e7771be, subnet-05ec2c8cceb939349]
    LifestyleGateway:
        Type: AWS::Serverless::Function
        Properties:
            Description: update video view count
            FunctionName: lifestyle-updateitem
            Handler: cron_update_view.update_item
            MemorySize: 128
            Role: arn:aws:iam::794633948264:role/lifestyle-lambda-role
            Runtime: python3.6
            CodeUri: ../
            Timeout: 900
            VpcConfig:
                SecurityGroupIds: [sg-053b844bbd96ee0cc]
                SubnetIds: [subnet-047d1ae6d1e7771be, subnet-05ec2c8cceb939349]
    LifestyleApi:
        Type: AWS::Serverless::Function
        Properties:
            Description: Lifestyle api function
            FunctionName: lifestyle-api
            Handler: lifestyle_api.apiHandler
            MemorySize: 128
            Role: arn:aws:iam::794633948264:role/lifestyle-lambda-role
            Runtime: nodejs8.10
            CodeUri: ../
            Timeout: 30
            VpcConfig:
                SecurityGroupIds: [sg-053b844bbd96ee0cc]
                SubnetIds: [subnet-047d1ae6d1e7771be, subnet-05ec2c8cceb939349]

    lifestyleBackendApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: prd
            DefinitionUri: ../lifestyle-backend-api.json
