AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Test automatic deployment or update of Lambda functions
Resources:
    LifestyleGateway:
        Type: AWS::Serverless::Function
        Properties:
            Description: Gateway for Lifestyle
            FunctionName: lifestyle-gateway
            Handler: lambda_function.lambda_handler
            MemorySize: 128
            Role: arn:aws:iam::XXXXX:role/lifestyle-lambda-role
            Runtime: python3.6
            CodeUri: ../
            Timeout: 30
            VpcConfig:
                SecurityGroupIds: [sg-XXX]
                SubnetIds: [subnet-XXX, subnet-XXX]
    lifestyleBackendApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: dev
            DefinitionUri: ../lifestyle-backend-api.json
