AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Test automatic deployment or update of Lambda functions
Resources:
    LifestyleGateway:
        Type: AWS::Serverless::Function
        Properties:
            Description: Gateway for Lifestyle
            FunctionName: lifestyle-gateway
            Handler: lambda_function.lambda_handler
            MemorySize: 128
            Role: arn:aws:iam::794633948264:role/lifestyle-lambda-role
            Runtime: python3.6
            CodeUri: ../
            Timeout: 30
            VpcConfig:
                SecurityGroupIds: [sg-050f5a0020464fcce]
                SubnetIds: [subnet-0a538231b976a732c, subnet-09539b2304c96020f]
    lifestyleBackendApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: dev
            DefinitionUri: ../lifestyle-backend-api.json
